settings:
  botname: {name}
  token: {token}
  developer: {name}
spring:
  datasource:
    url: {url}
    driver-class-name: "org.postgresql.Driver"
    password: {password}
    username: {user}
web:
  token: {token}
---
settings:
  botname: {name}
  token: {token}
  developer: {name}
spring:
  datasource:
    url: {url}
    driver-class-name: "org.postgresql.Driver"
    password: {password}
    username: {user}
  profiles: production
web:
  token: {token}



